using GildedRose.Entities;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
using System.Threading.Tasks;

namespace GildedRose.Repositories
{
    /// <summary>
    /// Contains the common elements of an entity repository.
    /// </summary>
    /// <typeparam name="T">The entity type</typeparam>
    public class RepositoryBase<T> : IRepository<T> where T : class, IEntity
    {
        private readonly DbContext _context;

        public RepositoryBase(DbContext context)
        {
            _context = context;

            // Uncomment this line to see the SQL queries generated by EF in the console window
            //_context.Database.Log = s => System.Diagnostics.Debug.WriteLine(s);
        }

        /// <summary>
        /// Gets the DbContext for this instance.
        /// </summary>
        protected DbContext Context
        {
            get { return _context; }
        }

        /// <summary>
        /// Gets the entity with the specified unique identifier.
        /// </summary>
        /// <param name="id">The unique identifier.</param>
        /// <returns>
        /// The corresponding entity.
        /// </returns>
        public virtual T Get(Guid id)
        {
            return Context.Set<T>().FirstOrDefault(e => e.Id == id);
        }

        public virtual IEnumerable<T> GetByParentId(Guid id)
        {
            return Context.Set<T>().Where(e => e.Id == id);
        }

        /// <summary>
        /// Gets the entities identified by the specified filter.
        /// </summary>
        /// <param name="filter">The filter.</param>
        /// <param name="orderBy">The order by.</param>
        /// <returns>A collection of filtered entities.</returns>
        public virtual IEnumerable<T> Get(Expression<Func<T, bool>> filter = null, Func<IQueryable<T>, IOrderedQueryable<T>> orderBy = null)
        {
            IQueryable<T> query = GetFilteredQuery(filter);
            return orderBy != null ? orderBy(query).ToList() : query.ToList();
        }

        /// <summary>
        /// Gets the filtered query.
        /// </summary>
        /// <param name="filter">The filter.</param>
        /// <returns></returns>
        private IQueryable<T> GetFilteredQuery(Expression<Func<T, bool>> filter = null)
        {
            return filter == null ? Context.Set<T>() : Context.Set<T>().Where(filter);
        }

        /// <summary>
        /// Saves the changed entities
        /// </summary>
        public virtual void Save()
        {
            Context.SaveChanges();
        }
        
        /// <summary>
        /// Creates the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        public void Create(T entity)
        {
            Context.Set<T>().Add(entity);
        }

        /// <summary>
        /// Deletes the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        public virtual void Delete(T entity)
        {
            Context.Entry(entity).State = EntityState.Deleted;
        }

        /// <summary>
        /// Deletes the specified entities.
        /// </summary>
        /// <param name="entities">The entities.</param>
        public virtual void Delete(IEnumerable<T> entities)
        {
            entities.ToList().ForEach(Delete);
        }

        /// <summary>
        /// Deletes the entities identified by the specified filter.
        /// </summary>
        /// <param name="filter">The filter.</param>
        public virtual void Delete(Expression<Func<T, bool>> filter)
        {
            Context.Set<T>().Where(filter).ToList().ForEach(Delete);
        }

        /// <summary>
        /// Gets the count of entities that meet the specified filter.
        /// </summary>
        /// <param name="filter">The filter.</param>
        /// <returns>The count of entities that meet the specified filter.</returns>
        public virtual int Count(Expression<Func<T, bool>> filter = null)
        {
            return GetFilteredQuery(filter).Count();
        }

        /// <summary>
        /// Indicates if any entities exist that match the specified filter
        /// </summary>
        /// <param name="filter">The entity filter.</param>
        /// <returns>true if there are matches, false otherwise.</returns>
        public virtual bool Exists(Expression<Func<T, bool>> filter)
        {
            return Count(filter) > 0;
        }

        /// <summary>
        /// Performs application-defined tasks associated with freeing, releasing, or resetting unmanaged resources.
        /// </summary>
        public void Dispose()
        {
            Context.Dispose();
        }
    }
}
